### ISSUE TITLE
Unable to read filtered count

### ISSUE THREAD

**Issue by phunkei** [mattiash/angular-tablesort#20] opened 2015-03-20 17:26 UTC
I'm using a simple text input as filter for my rows in the table.
The rows are filtered correctly with tablesort, but the temporary variable I use for counting filtered/total is empty now.

Example:

```html
<input type="search" ng-model="search" placeholder="Filter"/>
<span>Count: ({{filtered.length}}/{{projects.length}})</span>
<tr ng-repeat="project in filtered = (projects | filter: search)" ts-repeat>...
```
`filtered.length` should give me the amount of rows left (It does without tablesort).

**Comment by mattiash** [comment] 2015-03-21 22:32
I think that this can be solved with the same type of solution as in issue #11. The problem is that tablesort adds a "| tablesortOrderBy:sortFun" at the end of your ng-repeat which  doesn't work. If someone solves #11, you could write ng-repeat="project in filtered = (projects | filter: search | tablesort)" to make it work.

**Comment by mattiash** [comment] 2015-03-25 20:31
Closing now that #11 is fixed.

**Closed by mattiash** 2015-03-25 20:31 UTC
